using System;

namespace Mythosia.AI.Rag
{
    /// <summary>
    /// Context passed to Agentic RAG per-call query option callbacks.
    /// </summary>
    public sealed class AgenticRagQueryContext
    {
        public AgenticRagQueryContext(string toolName, string query)
        {
            ToolName = toolName ?? throw new ArgumentNullException(nameof(toolName));
            Query = query ?? throw new ArgumentNullException(nameof(query));
        }

        /// <summary>
        /// The registered tool name currently being executed.
        /// </summary>
        public string ToolName { get; }

        /// <summary>
        /// The self-contained query generated by the agent for this search step.
        /// </summary>
        public string Query { get; }
    }

    /// <summary>
    /// Structured trace payload emitted for each Agentic RAG tool execution.
    /// </summary>
    public sealed class AgenticRagSearchTrace
    {
        public AgenticRagSearchTrace(
            string toolName,
            string query,
            RagQueryOptions? queryOptions,
            RagProcessedQuery? result,
            Exception? exception = null)
        {
            ToolName = toolName ?? throw new ArgumentNullException(nameof(toolName));
            Query = query ?? throw new ArgumentNullException(nameof(query));
            QueryOptions = queryOptions;
            Result = result;
            Exception = exception;
        }

        /// <summary>
        /// The registered tool name that produced this trace item.
        /// </summary>
        public string ToolName { get; }

        /// <summary>
        /// The self-contained search query executed for this step.
        /// </summary>
        public string Query { get; }

        /// <summary>
        /// The resolved per-call query options.
        /// </summary>
        public RagQueryOptions? QueryOptions { get; }

        /// <summary>
        /// The structured query result for successful executions.
        /// Null when the tool failed before a result was produced.
        /// </summary>
        public RagProcessedQuery? Result { get; }

        /// <summary>
        /// The exception thrown while resolving query options or executing the search.
        /// Null when the tool completed successfully.
        /// </summary>
        public Exception? Exception { get; }

        /// <summary>
        /// Whether the search completed successfully.
        /// </summary>
        public bool Succeeded => Exception == null;

        /// <summary>
        /// Whether the successful result contains at least one reference.
        /// </summary>
        public bool HasReferences => Result?.HasReferences == true;
    }
}
