using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;
using System.Threading.Tasks;
using Mythosia.AI.Models;

namespace Mythosia.AI.Models.Functions
{
    /// <summary>
    /// Represents a function that can be called by AI
    /// </summary>
    public class FunctionDefinition
    {
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public FunctionParameters Parameters { get; set; }
        private Func<Dictionary<string, object>, Task<string>>? _handler;
        private Func<Dictionary<string, object>, CancellationToken, Task<string>>? _handlerWithCancellation;

        /// <summary>
        /// Gets or replaces the tool handler. This compatibility view invokes a cancellation-aware
        /// handler with CancellationToken.None when called directly. Setting either handler property
        /// replaces the same callable; handlers registered here do not receive execution cancellation.
        /// </summary>
        public Func<Dictionary<string, object>, Task<string>>? Handler
        {
            get => _handler;
            set
            {
                _handler = value;
                if (value == null) _handlerWithCancellation = null;
                else _handlerWithCancellation = (arguments, token) => value(arguments);
            }
        }

        /// <summary>
        /// Gets or replaces the tool handler that receives execution cancellation. Pass the token
        /// to cancellable operations to stop cooperatively. Setting this also updates Handler.
        /// </summary>
        public Func<Dictionary<string, object>, CancellationToken, Task<string>>? HandlerWithCancellation
        {
            get => _handlerWithCancellation;
            set
            {
                _handlerWithCancellation = value;
                if (value == null) _handler = null;
                else _handler = arguments => value(arguments, CancellationToken.None);
            }
        }

        /// <summary>
        /// Allows a supporting model and API to continue working while this function executes.
        /// Defaults to false. Unsupported providers use the ordinary blocking tool-call flow
        /// without changing this setting.
        /// </summary>
        public bool AllowAsync { get; set; }

        public FunctionDefinition()
        {
            Parameters = new FunctionParameters();
        }
    }

    /// <summary>
    /// Represents function parameters schema
    /// </summary>
    public class FunctionParameters
    {
        public string Type { get; set; } = "object";
        public Dictionary<string, ParameterProperty> Properties { get; set; }
        public List<string> Required { get; set; }

        public FunctionParameters()
        {
            Properties = new Dictionary<string, ParameterProperty>();
            Required = new List<string>();
        }
    }

    /// <summary>
    /// Represents a single parameter property
    /// </summary>
    public class ParameterProperty
    {
        public string Type { get; set; } = string.Empty;
        public string? Description { get; set; }
        public List<string>? Enum { get; set; }
        public object? Default { get; set; }
        public ParameterProperty? Items { get; set; }
    }

    /// <summary>
    /// ID source for function calls
    /// </summary>
    public enum IdSource
    {
        Library,    // Generated by our library
        OpenAI,     // Generated by OpenAI
        Claude,     // Generated by Claude
        Gemini,     // Generated by Gemini
        DeepSeek,   // Generated by DeepSeek
        Perplexity  // Generated by Perplexity
    }

    /// <summary>
    /// Represents a function call from AI
    /// </summary>
    public class FunctionCall
    {
        /// <summary>
        /// The original ID from the source
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Where this ID came from
        /// </summary>
        public IdSource Source { get; set; }

        /// <summary>
        /// Function name
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Whether the provider marked this call as asynchronous. Execution also requires
        /// provider support and the registered function's AllowAsync opt-in.
        /// </summary>
        public bool IsAsync { get; set; }

        /// <summary>
        /// Function arguments
        /// </summary>
        public Dictionary<string, object> Arguments { get; set; }

        /// <summary>
        /// Stable provider-assigned position used to correlate streaming call and result events.
        /// It can contain gaps when the provider interleaves non-function output items.
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Provider-specific data that must travel with this call, such as a Gemini thought signature.
        /// </summary>
        public Dictionary<string, object>? Metadata { get; set; }

        public FunctionCall()
        {
            Arguments = new Dictionary<string, object>();
        }

        internal FunctionCall Clone()
        {
            return new FunctionCall
            {
                Id = Id,
                Source = Source,
                Name = Name,
                IsAsync = IsAsync,
                Arguments = ObjectGraphSnapshot.CloneDictionary(Arguments),
                Index = Index,
                Metadata = ObjectGraphSnapshot.CloneNullableDictionary(Metadata)
            };
        }
    }

    /// <summary>
    /// All function calls requested by one assistant response, in provider order.
    /// </summary>
    public sealed class FunctionCallBatch
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public IReadOnlyList<FunctionCall> Calls { get; set; } = Array.Empty<FunctionCall>();
        public Dictionary<string, object>? Metadata { get; set; }

        public FunctionCallBatch()
        {
        }

        public FunctionCallBatch(IEnumerable<FunctionCall> calls)
        {
            if (calls == null)
                Calls = Array.Empty<FunctionCall>();
            else
                Calls = calls.ToList();
        }

        internal FunctionCallBatch Clone()
        {
            return new FunctionCallBatch(Calls.Select(call => call.Clone()))
            {
                Id = Id,
                Metadata = ObjectGraphSnapshot.CloneNullableDictionary(Metadata)
            };
        }
    }

    /// <summary>
    /// Result of one function call.
    /// </summary>
    public sealed class FunctionCallResult
    {
        public FunctionCall Call { get; set; } = new FunctionCall();
        public string Content { get; set; } = string.Empty;
        public bool IsError { get; set; }

        /// <summary>
        /// Whether execution was cancelled or skipped because cancellation was requested.
        /// The executor also sets IsError so providers cannot interpret cancellation as success.
        /// </summary>
        public bool IsCancelled { get; set; }

        internal FunctionCallResult Clone()
        {
            return new FunctionCallResult
            {
                Call = Call.Clone(),
                Content = Content,
                IsError = IsError,
                IsCancelled = IsCancelled
            };
        }
    }

    /// <summary>
    /// Results for one function-call batch. Ordinary execution preserves provider order;
    /// native asynchronous execution can deliver completed subsets in separate result batches.
    /// </summary>
    public sealed class FunctionCallResultBatch
    {
        public string FunctionCallBatchId { get; set; } = string.Empty;
        public IReadOnlyList<FunctionCallResult> Results { get; set; } = Array.Empty<FunctionCallResult>();

        public FunctionCallResultBatch()
        {
        }

        public FunctionCallResultBatch(string functionCallBatchId, IEnumerable<FunctionCallResult> results)
        {
            FunctionCallBatchId = functionCallBatchId;
            if (results == null)
                Results = Array.Empty<FunctionCallResult>();
            else
                Results = results.ToList();
        }

        internal FunctionCallResultBatch Clone()
        {
            return new FunctionCallResultBatch(
                FunctionCallBatchId,
                Results.Select(result => result.Clone()));
        }
    }

    /// <summary>
    /// Copies mutable JSON-like data carried by function calls. JSON elements are detached from
    /// their owning document, and JSON nodes, dictionaries, lists and arrays are copied so handlers
    /// and stream consumers cannot rewrite stored call history.
    /// </summary>
    internal static class ObjectGraphSnapshot
    {
        public static Dictionary<string, object> CloneDictionary(
            Dictionary<string, object>? source)
        {
            if (source == null)
                return new Dictionary<string, object>();

            return (Dictionary<string, object>)CloneValue(
                source,
                new Dictionary<object, object>(ReferenceIdentityComparer.Instance))!;
        }

        public static Dictionary<string, object>? CloneNullableDictionary(
            Dictionary<string, object>? source)
        {
            return source == null ? null : CloneDictionary(source);
        }

        private static object? CloneValue(
            object? value,
            Dictionary<object, object> visited,
            Action<object>? onCloneCreated = null)
        {
            if (value == null || value is string)
            {
                if (value != null) onCloneCreated?.Invoke(value);
                return value;
            }

            if (visited.TryGetValue(value, out var existing))
            {
                onCloneCreated?.Invoke(existing);
                return existing;
            }

            if (TryCloneJsonValue(value, out var jsonClone))
            {
                visited[value] = jsonClone!;
                onCloneCreated?.Invoke(jsonClone!);
                return jsonClone;
            }

            if (value.GetType().IsValueType)
            {
                onCloneCreated?.Invoke(value);
                return value;
            }

            if (value is Dictionary<string, object> stringDictionary)
            {
                var clone = new Dictionary<string, object>(stringDictionary.Comparer);
                visited[value] = clone;
                onCloneCreated?.Invoke(clone);
                foreach (var item in stringDictionary)
                    clone[item.Key] = CloneValue(item.Value, visited)!;
                return clone;
            }

            if (TryGetReadOnlyBacking(value, out var backing))
            {
                object? clone = null;
                CloneValue(backing, visited, clonedBacking =>
                {
                    clone = Activator.CreateInstance(value.GetType(), clonedBacking)!;
                    // A read-only view can occur inside its own backing collection. Publish
                    // the view when the backing copy is created, before copying its contents.
                    visited[value] = clone;
                    onCloneCreated?.Invoke(clone);
                });
                return clone;
            }

            if (value is Array array)
            {
                // Preserve the CLR array type, rank and lower bounds before detaching elements.
                var clone = (Array)array.Clone();
                visited[value] = clone;
                onCloneCreated?.Invoke(clone);
                if (array.LongLength == 0) return clone;
                var indices = Enumerable.Range(0, array.Rank).Select(array.GetLowerBound).ToArray();
                while (true)
                {
                    clone.SetValue(CloneValue(array.GetValue(indices), visited), indices);
                    var dimension = array.Rank - 1;
                    while (dimension >= 0 && indices[dimension] == array.GetUpperBound(dimension))
                    {
                        indices[dimension] = array.GetLowerBound(dimension);
                        dimension--;
                    }
                    if (dimension < 0) break;
                    indices[dimension]++;
                }
                return clone;
            }

            if (value is IDictionary dictionary)
            {
                var clone = CreateDictionaryWithComparer(dictionary) ?? new Hashtable();
                visited[value] = clone;
                onCloneCreated?.Invoke(clone);
                foreach (DictionaryEntry item in dictionary)
                    clone[CloneValue(item.Key, visited)!] = CloneValue(item.Value, visited);
                return clone;
            }

            if (value is IList list)
            {
                var clone = TryCreate<IList>(value.GetType()) ?? new ArrayList();
                visited[value] = clone;
                onCloneCreated?.Invoke(clone);
                foreach (var item in list)
                    clone.Add(CloneValue(item, visited));
                return clone;
            }

            // Unknown provider-specific reference types are treated as immutable.
            onCloneCreated?.Invoke(value);
            return value;
        }

        private static bool TryGetReadOnlyBacking(object value, out object? backing)
        {
            backing = null;
            var type = value.GetType();
            if (!type.IsGenericType) return false;
            var definition = type.GetGenericTypeDefinition();
            var propertyName = definition == typeof(ReadOnlyCollection<>) ? "Items"
                : definition == typeof(ReadOnlyDictionary<,>) ? "Dictionary"
                : null;
            if (propertyName == null) return false;

            // Only these exact BCL wrappers are inspected. Their protected accessors expose
            // the backing collection without invoking user-defined cloning or getter code.
            backing = type.GetProperty(propertyName, BindingFlags.Instance | BindingFlags.NonPublic)!
                .GetValue(value);
            return true;
        }

        private static bool TryCloneJsonValue(object value, out object? clone)
        {
            clone = null;
            var type = value.GetType();
            // Abstractions does not require a JSON package. Bridge only the known System.Text.Json
            // types when present; never discover arbitrary caller-defined cloning methods.
            if (type.Assembly.GetName().Name != "System.Text.Json")
                return false;

            try
            {
                MethodInfo? method = null;
                if (type.FullName == "System.Text.Json.JsonElement")
                {
                    // Undefined is the default struct value and has no owner to detach.
                    // Calling JsonElement.Clone on it throws on supported JSON runtimes.
                    if (Convert.ToInt32(type.GetProperty("ValueKind")!.GetValue(value)) == 0)
                    {
                        clone = value;
                        return true;
                    }
                    method = type.GetMethod("Clone", Type.EmptyTypes);
                }
                else
                {
                    for (var current = type; current != null; current = current.BaseType)
                    {
                        if (current.FullName != "System.Text.Json.Nodes.JsonNode") continue;
                        method = current.GetMethod("DeepClone", Type.EmptyTypes)
                            ?? throw new NotSupportedException("Snapshotting JSON nodes requires System.Text.Json with JsonNode.DeepClone support.");
                        break;
                    }
                }
                if (method == null) return false;
                clone = method.Invoke(value, null);
            }
            catch (TargetInvocationException exception) when (exception.InnerException != null)
            {
                ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
                throw;
            }
            return true;
        }

        private static IDictionary? CreateDictionaryWithComparer(IDictionary source)
        {
            var type = source.GetType();
            if (type == typeof(Hashtable) || type == typeof(SortedList))
            {
                // The BCL clone preserves comparer settings that have no public getter.
                var clone = (IDictionary)((ICloneable)source).Clone();
                clone.Clear();
                return clone;
            }
            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                // These exact BCL types expose comparer constructors. Keep custom container
                // behavior on the existing fallback path rather than inspecting arbitrary properties.
                if (definition == typeof(Dictionary<,>) || definition == typeof(SortedDictionary<,>) ||
                    definition == typeof(SortedList<,>))
                {
                    var comparer = type.GetProperty("Comparer")!.GetValue(source);
                    return (IDictionary)Activator.CreateInstance(type, comparer)!;
                }
            }
            return TryCreate<IDictionary>(type);
        }

        private static T? TryCreate<T>(Type type)
            where T : class
        {
            try
            {
                return Activator.CreateInstance(type) as T;
            }
            catch
            {
                return null;
            }
        }

        private sealed class ReferenceIdentityComparer : IEqualityComparer<object>
        {
            public static ReferenceIdentityComparer Instance { get; } = new ReferenceIdentityComparer();

            public new bool Equals(object? x, object? y) => ReferenceEquals(x, y);

            public int GetHashCode(object obj) => RuntimeHelpers.GetHashCode(obj);
        }
    }

    /// <summary>
    /// Function call mode
    /// </summary>
    public enum FunctionCallMode
    {
        None,   // Don't call functions
        Auto,   // AI decides when to call
    }

    /// <summary>
    /// Message metadata keys for standardization
    /// </summary>
    public static class MessageMetadataKeys
    {
        public const string MessageType = "message_type";  // "function_call" or "function_result"
        public const string FunctionId = "function_id";    // The original function ID
        public const string FunctionSource = "function_source";  // ID source (OpenAI, Claude, etc)
        public const string FunctionName = "function_name";
        public const string FunctionArguments = "function_arguments";
        public const string FunctionBatchId = "function_batch_id";
        public const string FunctionCount = "function_count";

        // For preserving original message structure
        public const string OriginalContent = "original_content";

        // Gemini 3 Thought Signatures
        public const string ThoughtSignature = "thought_signature";
    }
}
