<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\loaders\Mythosia.Documents.Hwp\Mythosia.Documents.Hwp.csproj" />
    <ProjectReference Include="..\..\src\loaders\Mythosia.Documents.Abstractions\Mythosia.Documents.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\loaders\Mythosia.Documents.Office\Mythosia.Documents.Office.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
